networks:
  mynetwork:
    driver: bridge

services:
  mysql:
    image: docker.io/mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bdvirtus
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  phpmyadmin:
    image: docker.io/phpmyadmin:latest
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql  
      PMA_USER: user
      PMA_PASSWORD: password
    networks:
      - mynetwork